name = "Inmation"
uuid = "199f2b5a-048b-44cc-a037-5c92511205ff"
authors = ["Ruben Gonzalez <ruben.carbonbased@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
